<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>

    <script>
        // promise是用来优化异步操作:

        //1、查出当前用户信息
        //2、按照当前用户的id查出他的课程
        //3、按照当前课程id查出分数
        $.ajax({
            url: "mock/user.json",
            success(data) {
                console.log("查询用户：", data);
                $.ajax({
                    // 再查询这个用户的课程
                    url: `mock/user_corse_${data.id}.json`,
                    success(data) { // 成功了执行这个方法
                        console.log("查询到课程：", data);
                        $.ajax({
                            // 再查询这个用户的分数
                            url: `mock/corse_score_${data.id}.json`,
                            success(data) {
                                console.log("查询到分数：", data);
                            },
                            error(error) { // 失败了执行这个方法
                                console.log("出现异常了：" + error);
                            }
                        });
                    },
                    error(error) {
                        console.log("出现异常了：" + error);
                    }
                });
            },
            error(error) {// 失败了执行这个方法
                console.log("出现异常了：" + error);
            }
        });


        //1、Promise可以封装异步操作
        // 语法格式:
        let p = new Promise((resolve, reject) => {
            //1、异步操作
            $.ajax({
                url: "mock/user.json",
                success: function (data) {
                    console.log("查询用户成功:", data)
                    resolve(data);
                },
                error: function (err) {
                    reject(err);
                }
            });
        });

        // p这个Promise操作成功之后,继续处理,参数obj就是上面resolve中的data (data就是上一步resolve传下来的对象)
        // 也就是p.then()会自动把上面resolve中的data传下来
        // p.then()相当于是promise对象拥有的方法
        p.then((obj) => {
            // 继续创建Promise来发请求
            return new Promise((resolve, reject) => {
                $.ajax({
                    url: `mock/user_corse_${obj.id}.json`,
                    success: function (data) {
                        console.log("查询用户课程成功:", data)
                        resolve(data);
                    },
                    error: function (err) {
                        reject(err)
                    }
                });
            })
        }).then((data) => { // 会把上一步的resolve的data继续传过来
            console.log("上一步的结果", data)
            $.ajax({
                url: `mock/corse_score_${data.id}.json`,
                success: function (data) {
                    console.log("查询课程得分成功:", data)
                },
                error: function (err) {
                }
            });
        }).catch((err) => { // 失败了以后怎么做.
            console.log("出现异常", err)
        });

        ///////////////////////////////////////////////////
        // 继续改进.
        function get(url, data) {
            // 返回一个Promise对象之后,可以.then(),.then()的来做事
            return new Promise((resolve, reject) => {
                $.ajax({
                    url: url,
                    data: data,
                    success: function (data) {
                        resolve(data);
                    },
                    error: function (err) {
                        reject(err)
                    }
                })
            });
        }

        get("mock/user.json")
            .then((data) => { // 有哪位返回的是Promise,所以可以继续.then()
                console.log("用户查询成功~~~:", data)
                return get(`mock/user_corse_${data.id}.json`);
            })
            .then((data) => {
                console.log("课程查询成功~~~:", data)
                return get(`mock/corse_score_${data.id}.json`);
            })
            .then((data) => {
                console.log("课程成绩查询成功~~~:", data)
            })
            .catch((err) => {
                console.log("出现异常", err)
            });

    </script>
</body>

</html>